"""add_assignee_names_to_workflow

Revision ID: 1bc05a0fa234
Revises: bba84e1aa0eb
Create Date: 2026-02-19 08:49:49.225025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bc05a0fa234'
down_revision: Union[str, Sequence[str], None] = 'bba84e1aa0eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('assignee_names', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'assignee_names')
    # ### end Alembic commands ###
