"""add_reviewers_and_agents

Revision ID: 29bbeee2f22c
Revises: 3035e5f8af88
Create Date: 2026-03-18 00:07:31.087079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29bbeee2f22c'
down_revision: Union[str, Sequence[str], None] = '3035e5f8af88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.add_column('workflow_assignments', sa.Column('agent_id', sa.Integer(), nullable=True))
    op.add_column('workflow_assignments', sa.Column('role', sa.String(), nullable=True))
    op.alter_column('workflow_assignments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'workflow_assignments', 'agents', ['agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow_assignments', type_='foreignkey')
    op.alter_column('workflow_assignments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('workflow_assignments', 'role')
    op.drop_column('workflow_assignments', 'agent_id')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
