"""add_tags_to_workflow

Revision ID: 3035e5f8af88
Revises: f0b9e3c4a1d2
Create Date: 2026-03-17 23:32:58.540049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3035e5f8af88'
down_revision: Union[str, Sequence[str], None] = 'f0b9e3c4a1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'tags')
    # ### end Alembic commands ###
